version: "3.8"
volumes:
  db-store:
services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: multi-php
    volumes:
      - ./src:/var/www/src

  nginx:
    image: nginx:1.19.6-alpine
    container_name: multi-nginx
    volumes:
      - ./nginx/nginx.conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/src
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
    depends_on:
      - php

  mysql:
    build: ./mysql
    container_name: multi-mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/my.cnf
    ports:
      - 3306:3306
